### ISSUE TITLE
release reference implementations into the public domain

### ISSUE THREAD

**Issue by seedhammer** [BlockchainCommons/Research#125]
Some specifications, such as [BCR-2020-005](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md), are specified in terms of reference implementations. Ideally, specifications should be complete without those implementations, but if its unavoidable we propose them be released into the public domain for maximal interoperability.

Our concrete issue is that the [SeedHammer implementation](https://github.com/seedhammer/seedhammer/blob/main/LICENSE) is in the public domain and it adds friction to implement your specifications without becoming a derivative and thus having to include your license.

**Comment by ChristopherA** [comment]
All of our docs and code are licensed under the permissive BSD-2-Clause Plus Patent License. We have to do this any declaration of public domain does not does mean free from patent problems. 

All the Bitcoin BIPs are BSD-2-Clause license, which have less protection from patent issues. As our license is totally permissive, I don't see why public domain is required.

**Comment by seedhammer** [comment]
I'm not referring to patent problems, but that even a BSD-2-clause license requires:

> 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
> 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

We go out of our way for our code not be derivations of your implementation to keep all of our code in the public domain.

Note that you can offer both a bsd-2 license and a public domain "license".

**Comment by ChristopherA** [comment]
Thanks again for your interest in our open-source projects; we are hoping that you will contribute.

We share your enthusiasm for open and accessible software, and this commitment is what led us to choose the “BSD-2-Clause Plus Patent License” in the first place instead of a public domain solution. After considerable research, we found it the most pragmatic solution to a number of problems.

We have not adopted a dual-license methodology as you suggest for a couple of reasons, one legal, one logistical. In theory, it’s possible to dual license a piece of software - that is, to offer it under two or more separate licenses. However, a declaration to make something public domain is not a license and likely would invalidate the dual license. That’s the legal issue. The logistical one is simply that we’d need to gain consent from all contributors, as each would need to agree to the terms of each license. This can get quite complex and burdensome, especially for a large, collaborative project like ours.

More generally, though, we offer our code and specifications under the “BSD-2-Clause Plus Patent License” because they offer protections that public domain code can’t. In fact, many companies will not use public-domain work because of the lack of protections, and so our adoption of the BSD-2-Claus Plus Patent License helps to get our work out to the most people, in our opinion.

As one example, a public domain declaration does not inherently grant permission to use, modify, or distribute the software, which could deter potential users and contributors. However, the biggest problem, in our opinion, is that the public domain does not provide explicit patent protection, whereas the “BSD-2-Clause Plus Patent License” does. This means that you could start using public-domain code, and then get held up by a contributor who purposefully integrated technology whose concepts were protected by a patent.

Under our current license, any project contributor instead provides an implicit patent license, protecting other users from patent infringement claims related to the use of our software. Furthermore, the BSD-2-Clause Plus Patent License also includes an indemnity clause. This is a critical safeguard not typically inherent to public domain declarations, protecting contributors, distributors, and users from liability should legal issues arise.

There are other advantages: the “BSD-2-Clause Plus Patent License” serves as a “universal donor” to other open source projects due to its compatibility with many other open source licenses, including Apache and GPL. This compatibility widens the potential reach and collaborative possibilities of our software.

As [/dev/lawyer reports](https://writing.kemitchell.com/2019/11/07/BSD-Patents), the license has also received good attention from people that we respect. It’s “approved by the Free Software Foundation as ‘GPLv2-compatible’, and approved by the Open Source Initiative as ‘open source’. As of this writing, Blue Oak Council lists BSD-2-Clause-Patent as its sole gold-rated license, surpassed only by the council’s own model permissive license, which gives even broader patent assurance.”

While we appreciate and value the intent to maintain code in the public domain, we think that it’s crucial to balance this aspiration with legal and practical considerations that ensure the longevity and protection of open-source projects. We believe that the “BSD-2-Clause Plus Patent License” strikes an optimal balance between permissiveness, necessary protections, and compatibility with other open-source licenses.

We hope this explanation clarifies our perspective and reasoning. Your contribution under this license would be highly appreciated, and we’re more than willing to address any further questions or concerns you may have about it.

**Comment by seedhammer** [comment]
Thank you for your explanation. I'll close this by commenting on the two main (in my opinion) issues you bring up:

> We have not adopted a dual-license methodology as you suggest for a couple of reasons, one legal, one logistical. In theory, it’s possible to dual license a piece of software - that is, to offer it under two or more separate licenses. However, a declaration to make something public domain is not a license and likely would invalidate the dual license. 

A known counter-argument to putting works in the public domain invalidates other licenses is SQLite. SQLite is in the public domain, but the company behind if also offers [commercial licenses](https://www.sqlite.org/purchase/license).

> That’s the legal issue. The logistical one is simply that we’d need to gain consent from all contributors, as each would need to agree to the terms of each license. This can get quite complex and burdensome, especially for a large, collaborative project like ours.

Putting existing implementations into the public domain would be nice. However, this issue is primarily about future standards and their reference implementations. They don't have existing contributors, by definition.

I believe the rest of your post is about the advantages of your existing license, to which I agree, but also seems irrelevant to this issue. In particular, if this issue were adopted, any contributors would need to agree to both your BSD-2-plus-patents license in addition to putting their contribution into the public domain.
